version: '3.7'

services:
  geth-bootnode:
    hostname: geth-bootnode
    env_file:
      - .env
    image: ethereum/client-go:v1.10.1
    volumes:
      - geth-bootnode-volume:/root/.ethereum
    command:
      --nodekeyhex="b0ac22adcad37213c7c565810a50f1772291e7b0ce53fb73e7ec2a3c75bc13b5"
      --nodiscover
      --ipcdisable
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.255.0/28"
    networks:
      priv-eth-net:
    restart: always

  geth-rpc-endpoint:
    hostname: geth-rpc-endpoint
    env_file:
      - .env
    image: ethereum/client-go:v1.10.1
    depends_on:
      - geth-bootnode
    volumes:
      - geth-rpc-endpoint-volume:/root/.ethereum
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,personal"
      --http.corsdomain="*"
      --networkid=${NETWORK_ID}
      --rpcvhosts="*"
    ports:
      - "8545:8545"
      - "30303:30303"
    networks:
      priv-eth-net:
    restart: always

  geth-miner:
    hostname: geth-miner
    env_file:
      - .env
    image: ethereum/client-go:v1.10.1
    depends_on:
      - geth-bootnode
    volumes:
      - geth-miner-volume:/root/.ethereum
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --mine
      --miner.threads=1
      --miner.etherbase=${MINER_ETHERBASE_WALLET}
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.255.0/28"
    networks:
      priv-eth-net:
    restart: always

  geth-explorer:
    hostname: geth-explorer
    env_file:
      - .env-explorer
    image: alethio/ethereum-lite-explorer
    ports:
      - "80:80"
    depends_on:
      - geth-rpc-endpoint
    networks:
      priv-eth-net:
    restart: always

  eth-net-intelligence-api:
    hostname: eth-net-intelligence-api
    image: registry.carakan.id/blockchain/eth-net-intelligence-api:v1.0
    volumes:
      - ./app.json:/home/ethnetintel/eth-net-intelligence-api/app.json
    depends_on:
      - geth-rpc-endpoint
    networks:
      priv-eth-net:
    restart: always

  eth-netstat:
    hostname: eth-netstat
    image: registry.carakan.id/blockchain/ethnetstat:v1.1
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - eth-net-intelligence-api
    networks:
      priv-eth-net:
    restart: always

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.255.0/28

volumes:
  geth-bootnode-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/.docker/geth-bootnode-volume

  geth-miner-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/.docker/geth-miner-volume

  geth-rpc-endpoint-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/.docker/geth-rpc-endpoint-volume
